tasks:
- init: ./mvnw package -DskipTests
  command: java -jar target/*.jar

# exposed ports
ports:
- port: 8080
  onOpen: open-preview

vscode:
  extensions:
    - dracula-theme.theme-dracula@2.22.3:c2qxutk2xT/UW8L9+9bW2g==